### ISSUE TITLE
Wrong pretrained weights?

### ISSUE THREAD

**Issue by xuduo35** [liyunsheng13/micronet#1]
md5sum *
f514ad5f6d691793cfca029f31d87128  micronet-m0.pth
f514ad5f6d691793cfca029f31d87128  micronet-m1.pth
f514ad5f6d691793cfca029f31d87128  micronet-m2.pth
f514ad5f6d691793cfca029f31d87128  micronet-m3.pth
All are the m3?

**Comment by liyunsheng13** [comment]
Thanks for letting me know. The correct models have been uploaded.

**Comment by xuduo35** [comment]
Thank you.
