### ISSUE TITLE
Micro-Factorized pointwise convolution

### ISSUE THREAD

**Issue by qdd1234** [liyunsheng13/micronet#13]
Hi, thanks for your wonderful work, I want to ask whether the proposed Micro-Factorized pointwise convolution is a plug and play model? I want to replace pointwise convolution with your Micro-Factorized pointwise convolution in MobileNetV3
.

**Comment by liyunsheng13** [comment]
Yes, it is a plug-and-play model. You have multiple choices to implement. Remember in our paper, we express Micro-Factorized convolution as a matrix decomposition- W = P \Phi Q. For mobilenet, you can view each pointwise convolution as W and decompose it to the multiplication of P\Phi Q. Another way is to view two consecutive pointwise convolutional layers as P and Q and change them to group conv with group number explained in our paper.

**Comment by qdd1234** [comment]
If I want to implement Micro-Factorized pointwise convolution in MobileNetV3 to replace pointwise convolution. Code L381-L397 and L349-L362 which is suitable?

**Comment by liyunsheng13** [comment]
You need to use both with order L381-L395 (P\Phi)+ L349-L363 (Q)

**Comment by qdd1234** [comment]
> You need to use both with order L381-L395 (P\Phi)+ L349-L363 (Q)

I see, Thanks!
