### ISSUE TITLE
requests for the code

### ISSUE THREAD

**Issue by WangChyanhassth-2say** [liyunsheng13/micronet#16]
Hi,
I've already read your paper and thought that's a wonderful job.
But when I try to read your code, I found those three blocks are not very clear in it. 
It confuses me cause I want to use them as the part of other models.
So it may be rude, but would you please rewrite the code with the 'Micro-Block-A, Micro-Block-B, and Micro-Block-C' description as it is in the paper.
Thank you very much! 

now the codes of the block looks like this:
'''

    ##StemLayer

    A  ## + MFDC + RELU + Shuffle1 + MFPC + act_layer + Shuffle1 + Shuffle2

    A  ## + MFDC + act_layer + Shuffle1 + Shuffle2 + MFPC + act_layer +Shuffle1 + Shuffle2

    A? ## + MFDC + act_layer + Shuffle1 + Shuffle2 + MFPC + act_layer +Shuffle1 + Shuffle2

    B? ## + MFPC + act_layer + Shuffle1 + MFDC + act_layer + Shuffle2 + MFPC + act_layer + Shuffle1 + Shuffle2

    C  ## + MFPC + act_layer + Shuffle1 + MFDC + act_layer + Shuffle2 + MFPC + act_layer + Shuffle1 + Shuffle2

    C  ## + MFPC + act_layer + Shuffle1 + MFDC + act_layer + Shuffle2 + MFPC + act_layer + Shuffle1 + Shuffle2

    C? ## + MFPC + act_layer
'''

but it should be like:

'''

    ##StemLayer

    A  ## + MFDC + RELU + Shuffle1 + MFPC + act_layer + Shuffle1 + Shuffle2

    A  ## + MFDC + act_layer + Shuffle1 + Shuffle2 + MFPC + act_layer + Shuffle1 + Shuffle2

    B  ## + MFDC + act_layer + Shuffle1 + Shuffle2 + MFPC + act_layer +Shuffle1 + Shuffle2 + MFPC + act_layer 

    C  ## + Shuffle1 + MFDC + act_layer + Shuffle2 + MFPC + act_layer + Shuffle1 + Shuffle2 + MFPC + act_layer

    C  ## + Shuffle1 + MFDC + act_layer + Shuffle2 + MFPC + act_layer + Shuffle1 + Shuffle2 + MFPC + act_layer

    C  ## + Shuffle1 + MFDC + act_layer + Shuffle2 + MFPC + act_layer + Shuffle1 + Shuffle2 + MFPC + act_layer

'''

**Comment by liyunsheng13** [comment]
Thanks for letting me know your confusion. Mathematically, my implementation is exact same as what I wrote in the paper. But I agree with you that the organization is different. I will update it when I have time.
