### ISSUE TITLE
Questions about the implementation

### ISSUE THREAD

**Issue by sayakpaul** [liyunsheng13/micronet#17]
Hi.

I am trying to implement MicroNet in TensorFlow. I am trying to understand the computation differences between `SpatialSepConvSF` and `DepthSpatialSepConv`. From the looks of it, their blocks look all the same to me barring the number of output channels that could have been efficiently parameterized through a single class I believe. 

The only difference seems to be the ChannelShuffle layer in the former i.e., the `SpatialSepConvSF` block. ChannelShuffle isn't mentioned in the paper as well.

Could you shed some light?

**Comment by liyunsheng13** [comment]
The implementation is very similar. The SpatialSepConvSF is used on layers with different input and output channels.
