### ISSUE TITLE
MaxGroupPooling Module not found!

### ISSUE THREAD

**Issue by sithu31296** [liyunsheng13/micronet#2]
I cannot find the code of MaxGroupPooling used in line 102 of micronet.py.
https://github.com/liyunsheng13/micronet/blob/main/backbone/micronet.py#L102
Can you check?

**Comment by liyunsheng13** [comment]
I add the MaxGroupPooling function. Thanks for letting me know. Actually, I do not use this function for MicroNet implementation. It is just used for ablation.

**Comment by sithu31296** [comment]
Thanks for the fast reply. I will re-check the code.
